from __future__ import annotations

import os
import re
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Any, Callable, Optional

import meshio
import numpy as np

def _scan_elsets(inp_path: Path) -> list[str]:
    elsets: list[str] = []
    pat = re.compile(r"^\*ELSET\s*,\s*ELSET\s*=\s*([^,\s]+)", re.IGNORECASE)
    with inp_path.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = pat.match(line.strip())
            if m:
                elsets.append(m.group(1))
    return elsets


def _write_beso_conf(
    target_path: Path,
    work_dir: Path,
    ccx_path: Path,
    file_name: str,
    elset_name: str,
    mass_goal_ratio: float,
    filter_radius: float,
    optimization_base: str,
    save_every: int,
) -> None:
    conf = f"""# Auto-generated by web agent (do not commit secrets)

path = r\"{work_dir}\"
path_calculix = r\"{ccx_path}\"
file_name = \"{file_name}\"

elset_name = \"{elset_name}\"
domain_optimized[elset_name] = True
domain_density[elset_name] = [1e-6, 1]
domain_thickness[elset_name] = [1.0, 1.0]
domain_offset[elset_name] = 0.0
domain_orientation[elset_name] = []
domain_FI[elset_name] = [[(\"stress_von_Mises\", 450.0e6)], [(\"stress_von_Mises\", 450.0)]]
domain_material[elset_name] = [\"*ELASTIC \\n210000e-6,  0.3\", \"*ELASTIC \\n210000,  0.3\"]
domain_same_state[elset_name] = False

mass_goal_ratio = {mass_goal_ratio}
filter_list = [[\"simple\", {filter_radius}]]
optimization_base = \"{optimization_base}\"
save_iteration_results = {save_every}
save_resulting_format = \"inp vtk\"
"""
    target_path.write_text(conf, encoding="utf-8")


def run_beso_job(
    workspace_root: Path,
    run_dir: Path,
    inp_path: Optional[str],
    mass_goal_ratio: float,
    filter_radius: float,
    optimization_base: str,
    save_every: int,
    cancel_flag: threading.Event,
    on_log: Callable[[str], None],
    on_vtk: Callable[[str], None],
    on_artifact: Callable[[dict[str, Any]], None] | None = None,
) -> None:
    workspace_root = workspace_root.resolve()
    run_dir = run_dir.resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    if not inp_path:
        raise ValueError("inp_path is required")
    inp_src = Path(inp_path).resolve()
    if not inp_src.exists():
        raise FileNotFoundError(inp_src)

    # Copy inp into run directory
    inp_dst = run_dir / inp_src.name
    shutil.copy2(inp_src, inp_dst)

    # Ensure we don't inherit FreeCAD/Python environment variables that can break subprocess resolution
    os.environ.pop("PYTHONHOME", None)
    os.environ.pop("PYTHONPATH", None)

    # Derive elset name
    elsets = _scan_elsets(inp_dst)
    elset_name = "SolidMaterialElementGeometry2D" if "SolidMaterialElementGeometry2D" in elsets else (elsets[0] if elsets else "all_available")

    # Locate ccx
    ccx_path = Path(os.environ.get("CCX_PATH", r"D:\freecad\bin\ccx.exe")).resolve()
    if not ccx_path.exists():
        raise FileNotFoundError(f"ccx not found: {ccx_path}")

    # Write a job-local beso_conf.py
    conf_path = run_dir / "beso_conf.py"
    _write_beso_conf(
        conf_path,
        work_dir=run_dir,
        ccx_path=ccx_path,
        file_name=inp_dst.name,
        elset_name=elset_name,
        mass_goal_ratio=mass_goal_ratio,
        filter_radius=filter_radius,
        optimization_base=optimization_base,
        save_every=save_every,
    )

    # Run beso_main.py, ensuring it loads our config (same dir). We do that by copying beso sources in.
    beso_src = (workspace_root / "beso").resolve()
    if not beso_src.exists():
        raise FileNotFoundError(f"beso source folder missing: {beso_src}")

    # Minimal set of files needed
    required = [
        "beso_main.py",
        "beso_lib.py",
        "beso_filters.py",
        "beso_plots.py",
        "beso_separate.py",
    ]
    for f in required:
        shutil.copy2(beso_src / f, run_dir / f)

    cmd = [
        os.environ.get("PYTHON_EXE", "python"),
        str(run_dir / "beso_main.py"),
        str(inp_dst),
    ]
    on_log(f"[CMD] {' '.join(cmd)}")

    env = os.environ.copy()
    # Force non-GUI rendering so Windows won't pop up plot windows.
    env.setdefault("MPLBACKEND", "Agg")

    proc = subprocess.Popen(
        cmd,
        cwd=str(run_dir),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        universal_newlines=True,
    )

    last_iter_seen: int = -1
    last_mesh_token: str | None = None
    last_img_mtime: dict[str, float] = {}
    try:
        while True:
            if cancel_flag.is_set():
                on_log("[INFO] cancelling job, terminating process...")
                proc.terminate()
                try:
                    proc.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    proc.kill()
                break

            line = proc.stdout.readline() if proc.stdout else ""
            if line:
                on_log(line.rstrip("\n"))

            # watcher: images
            if on_artifact:
                for name in ("Mass.png", "FI_mean.png", "FI_max.png", "FI_violated.png"):
                    p = run_dir / name
                    if not p.exists():
                        continue
                    m = p.stat().st_mtime
                    prev = last_img_mtime.get(name, 0.0)
                    if m > prev:
                        last_img_mtime[name] = m
                        on_artifact({"kind": "image", "path": name, "name": name})

            # watcher: prefer state1 inp frames (true topology result), fallback to vtk
            best_mesh_src: Path | None = None
            best_iter: int | None = None
            source_vtk_name: str | None = None

            state1_inps = list(run_dir.glob("file*_state1.inp"))
            for p in state1_inps:
                m = re.match(r"^file(\d+)_state1\.inp$", p.name, re.IGNORECASE)
                if not m:
                    continue
                it = int(m.group(1))
                if best_iter is None or it > best_iter:
                    best_iter = it
                    best_mesh_src = p
                    source_vtk_name = f"file{it:03d}.vtk"

            if best_mesh_src is None:
                vtk_files = list(run_dir.glob("file*.vtk"))
                best_vtk: Path | None = None
                for p in vtk_files:
                    m = re.match(r"^file(\d+)\.vtk$", p.name, re.IGNORECASE)
                    if not m:
                        continue
                    it = int(m.group(1))
                    if best_iter is None or it > best_iter:
                        best_iter = it
                        best_vtk = p
                if best_vtk is None:
                    rs = run_dir / "resulting_states.vtk"
                    if rs.exists():
                        best_vtk = rs
                        best_iter = last_iter_seen + 1
                if best_vtk is not None:
                    best_mesh_src = best_vtk
                    source_vtk_name = best_vtk.name if best_vtk.suffix.lower() == ".vtk" else None

            if best_mesh_src is not None and best_iter is not None:
                mesh_token = best_mesh_src.name
                should_update = (best_iter > last_iter_seen) or (mesh_token != last_mesh_token and mesh_token.startswith("file"))
                if not should_update:
                    if proc.poll() is not None:
                        break
                    time.sleep(0.05)
                    continue

                last_iter_seen = max(last_iter_seen, best_iter)
                last_mesh_token = mesh_token
                # write per-iteration obj so frontend can play frames
                frame_obj = run_dir / f"file{best_iter:03d}.obj"
                latest_obj = run_dir / "latest.obj"
                try:
                    mesh = meshio.read(best_mesh_src)
                    if best_mesh_src.suffix.lower() == ".vtk":
                        mesh = _filter_mesh_by_latest_state(mesh)
                    mesh = _strip_to_geometry(mesh)
                    meshio.write(frame_obj, mesh, file_format="obj")
                    # keep a stable pointer for "latest"
                    try:
                        latest_obj.write_text(frame_obj.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")
                    except Exception:
                        # fallback to copy bytes
                        shutil.copy2(frame_obj, latest_obj)

                    on_vtk(latest_obj.name)
                    if on_artifact:
                        on_artifact(
                            {
                                "kind": "mesh",
                                "path": frame_obj.name,
                                "name": frame_obj.name,
                                "meta": {"source_vtk": source_vtk_name, "iter": best_iter},
                            }
                        )
                except Exception as e:
                    on_log(f"[WARN] mesh->obj convert failed: {e}")
                    on_vtk(best_mesh_src.name)
                    if on_artifact:
                        on_artifact(
                            {"kind": "mesh", "path": best_mesh_src.name, "name": best_mesh_src.name, "meta": {"iter": best_iter}}
                        )

            if proc.poll() is not None:
                # drain remaining
                if proc.stdout:
                    for rest in proc.stdout:
                        on_log(rest.rstrip("\n"))
                break

            time.sleep(0.05)
    finally:
        try:
            if proc.poll() is None:
                proc.kill()
        except Exception:
            pass


def _filter_mesh_by_latest_state(mesh: meshio.Mesh) -> meshio.Mesh:
    """
    BESO vtk files contain per-iteration cell_data like element_states000, element_states010, ...
    We keep only elements with state > 0 in the latest available state field so the 3D preview
    reflects topology evolution instead of showing the full original domain.
    """
    state_keys = [k for k in mesh.cell_data.keys() if k.startswith("element_states")]
    if not state_keys:
        return mesh

    def _suffix_num(k: str) -> int:
        m = re.search(r"(\d+)$", k)
        return int(m.group(1)) if m else -1

    latest_key = max(state_keys, key=_suffix_num)
    states_per_block = mesh.cell_data.get(latest_key, [])
    if not states_per_block or len(states_per_block) != len(mesh.cells):
        return mesh

    filtered_cells = []
    for block, state_arr in zip(mesh.cells, states_per_block):
        arr = np.asarray(state_arr).ravel()
        if arr.size == 0:
            continue
        mask = arr > 0.5
        if np.any(mask):
            filtered_cells.append((block.type, block.data[mask]))

    if not filtered_cells:
        return mesh

    return meshio.Mesh(points=mesh.points, cells=filtered_cells)


def _strip_to_geometry(mesh: meshio.Mesh) -> meshio.Mesh:
    """
    Drop all cell/point data before writing OBJ to avoid incompatibilities
    from mismatched metadata lengths across iterations.
    """
    cells = [(c.type, c.data) for c in mesh.cells]
    return meshio.Mesh(points=mesh.points, cells=cells)

