# Auto-generated by web agent (do not commit secrets)

path = r"D:\python_project\beso_ai\examples\base\beso_output"
path_calculix = r"D:\freecad\bin\ccx.exe"
file_name = "BESO2_merged_for_beso.inp"

iterations_limit = 5
elset_name = "Eall"
domain_optimized[elset_name] = True
domain_density[elset_name] = [1e-6, 1]
domain_thickness[elset_name] = [1.0, 1.0]
domain_offset[elset_name] = 0.0
domain_orientation[elset_name] = []
domain_FI[elset_name] = [[("stress_von_Mises", 450.0e6)], [("stress_von_Mises", 450.0)]]
domain_material[elset_name] = ["*ELASTIC \n210000e-6,  0.3", "*ELASTIC \n210000,  0.3"]
domain_same_state[elset_name] = False

mass_goal_ratio = 0.25
filter_list = [["simple", 623.6258825191754]]
optimization_base = "failure_index"
save_iteration_results = 1
save_resulting_format = "inp vtk"
